[package]
name = "solarium-macros"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
solarium-workspace.workspace = true
syn = "2.0.29"
quote = "1.0.33"
proc-macro2 = "1"
anyhow.workspace = true

ligen-ir.workspace = true
ligen-rust-parser.workspace = true
ligen-parser.workspace = true

anchor-lang-idl-spec.workspace = true

serde_json.workspace = true