[package]
name = "solarium-client"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
solarium.workspace = true
solana-sdk.workspace = true
solana-program.workspace = true
solana-client.workspace = true
solana-account-decoder-client-types.workspace = true
tokio.workspace = true
futures.workspace = true
async-trait.workspace = true
shrinkwraprs.workspace = true
thiserror.workspace = true
