[package]
name = "solarium"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[features]
program = []
client = [ "tokio", "solana-sdk", "solana-client", "solana-account-decoder-client-types", "futures" ]

[dependencies]
solarium-macros.workspace = true
solana-program.workspace = true
solana-sdk = { workspace = true, optional = true }
solana-client = { workspace = true, optional = true }
solana-account-decoder-client-types = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
sha2.workspace = true
borsh.workspace = true
shrinkwraprs.workspace = true
thiserror.workspace = true
async-trait.workspace = true