[package]
name = "solarium"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
solarium-macros.workspace = true
solarium-pinocchio.workspace = true
borsh.workspace = true
sha2.workspace = true
