[package]
name = "solarium-cli"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "solarium"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
solarium-workspace.workspace = true
bytemuck_derive.workspace = true