[package]
name = "solarium-example"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["solana-program-backend"]
solana-program-backend = ["solarium-program/solana-program-backend"]
pinocchio = ["solarium-program/pinocchio"]
no-entrypoint = []

[dependencies]
solarium-program = { path = "../../crates/solarium-program", default-features = false }
solarium.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
tokio.workspace = true
anyhow.workspace = true
futures.workspace = true
solarium-client.workspace = true
