[package]
name = "solarium-workspace"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
solana-pubkey.workspace = true
solana-keypair.workspace = true
solana-signer.workspace = true
anyhow.workspace = true

ligen.workspace = true
ligen-rust.workspace = true
ligen-anchor.workspace = true

tokio.workspace = true
anchor-lang-idl-spec.workspace = true
serde_json.workspace = true
syn.workspace = true
walkdir.workspace = true
toml.workspace = true
