[package]
name = "solarium-program"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
solarium.workspace = true
shrinkwraprs.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
solana-program.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
solana-pubkey.workspace = true
solana-sha256-hasher = "2.1.0"
curve25519-dalek = "4.1"
