[package]
name = "solarium-program"
version.workspace = true
edition.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
solarium.workspace = true
solana-program.workspace = true
shrinkwraprs.workspace = true
thiserror.workspace = true
